server:
  port: ${SERVER_PORT:9999}

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: otus_highload
  datasource:
    master:
      jdbc-url: ${DATASOURCE_MASTER_URL:jdbc:postgresql://localhost:5432/postgres}
      url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
      username: postgres
      password: pass
      driver-class-name: org.postgresql.Driver
    slave:
      jdbc-url: ${DATASOURCE_SLAVE_URL:jdbc:postgresql://localhost:15432/postgres}
      url: ${DATASOURCE_URL:jdbc:postgresql://localhost:15432/postgres}
      username: postgres
      password: pass
      driver-class-name: org.postgresql.Driver
  liquibase:
    default-schema: ${DATASOURCE_DEFAULT_SCHEMA:otus_highload}

management:
  endpoints:
    web:
      exposure:
        include: 'prometheus, health'